<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.13">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotnetCrawler.Data\DotnetCrawler.Data.csproj" />
    <ProjectReference Include="..\DotnetCrawler.Downloader\DotnetCrawler.Downloader.csproj" />
    <ProjectReference Include="..\DotnetCrawler.Pipeline\DotnetCrawler.Pipeline.csproj" />
    <ProjectReference Include="..\DotnetCrawler.Processor\DotnetCrawler.Processor.csproj" />
    <ProjectReference Include="..\DotnetCrawler.Request\DotnetCrawler.Request.csproj" />
    <ProjectReference Include="..\DotnetCrawler.Scheduler\DotnetCrawler.Scheduler.csproj" />
  </ItemGroup>

</Project>
